begin
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Thomas", `last_name`:"Beier", `UNIQUE IMPORT ID`:0});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:1});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04101", `street`:"Radenerstraße", `street_number`:"6", `town`:"Leipzig", `UNIQUE IMPORT ID`:2});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`electronic_mail_address`:"tbeier@gmx.de", `telephone_number`:"034159312", `UNIQUE IMPORT ID`:3});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Josephin", `last_name`:"Schmidt", `UNIQUE IMPORT ID`:4});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`country`:"Deutschland", `postal_box`:"Postfach 3 11", `postal_code`:"04107", `UNIQUE IMPORT ID`:5});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04109", `street`:"Auengasse", `street_number`:"7", `town`:"Leipzig", `UNIQUE IMPORT ID`:6});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`telephone_number`:"034100499", `UNIQUE IMPORT ID`:7});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Maximilian", `last_name`:"Großmaurer", `UNIQUE IMPORT ID`:8});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:9});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04109", `street`:"Auengasse", `street_number`:"7", `town`:"Leipzig", `UNIQUE IMPORT ID`:10});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`telephone_number`:"034100499", `UNIQUE IMPORT ID`:11});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Bernhard", `last_name`:"Gasser", `UNIQUE IMPORT ID`:12});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:13});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04107", `street`:"Wartenstraße", `street_number`:"13", `town`:"Leipzig", `UNIQUE IMPORT ID`:14});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`electronic_mail_address`:"berndd@yahoo.de", `telephone_number`:"034115939", `UNIQUE IMPORT ID`:15});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Arnold", `last_name`:"Baumeister", `UNIQUE IMPORT ID`:16});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:17});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04107", `street`:"Grassistraße", `street_number`:"5", `town`:"Leipzig", `UNIQUE IMPORT ID`:18});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:19});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Inge", `last_name`:"Berghof", `UNIQUE IMPORT ID`:20});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:21});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04102", `street`:"Grinderallee", `street_number`:"22", `town`:"Leipzig", `UNIQUE IMPORT ID`:22});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`telephone_number`:"034133331", `UNIQUE IMPORT ID`:23});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Hans", `last_name`:"Obermann", `UNIQUE IMPORT ID`:24});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`country`:"Deutschland", `postal_box`:"Postfach 3 77", `postal_code`:"04101", `UNIQUE IMPORT ID`:25});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04109", `street`:"Prinzenstraße", `street_number`:"17", `town`:"Leipzig", `UNIQUE IMPORT ID`:26});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:27});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Brigitte", `last_name`:"Sturm", `UNIQUE IMPORT ID`:28});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:29});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04106", `street`:"Auen-Weiher-Straße", `street_number`:"1", `town`:"Leipzig", `UNIQUE IMPORT ID`:30});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`telephone_number`:"034154123", `UNIQUE IMPORT ID`:31});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Anelise", `last_name`:"Bursche", `UNIQUE IMPORT ID`:32});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:33});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04106", `street`:"Auen-Weiher-Straße", `street_number`:"5", `town`:"Leipzig", `UNIQUE IMPORT ID`:34});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`electronic_mail_address`:"bursche@google.de", `UNIQUE IMPORT ID`:35});
CREATE (:`Person`:`Party`:`UNIQUE IMPORT LABEL` {`first_name`:"Arsentia", `last_name`:"Wieland", `UNIQUE IMPORT ID`:36});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:37});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04107", `street`:"Großbaumstraße", `street_number`:"11", `town`:"Leipzig", `UNIQUE IMPORT ID`:38});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`telephone_number`:"034199419", `UNIQUE IMPORT ID`:39});
CREATE (:`External_object_reference`:`UNIQUE IMPORT LABEL` {`description`:"Windenergieanlage 5", `id`:"eorwea0005", `type`:"Windanlage", `UNIQUE IMPORT ID`:40});
CREATE (:`External_object_reference`:`UNIQUE IMPORT LABEL` {`description`:"Verwaltungsbüroanlage 2", `id`:"eorverw02", `type`:"Verwaltung", `UNIQUE IMPORT ID`:48});
CREATE (:`Party`:`Organisation`:`UNIQUE IMPORT LABEL` {`name`:"Anlagenbetreiber Reindorf GmbH", `UNIQUE IMPORT ID`:50});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04108", `street`:"Industriestraße", `street_number`:"2", `town`:"Leipzig", `UNIQUE IMPORT ID`:51});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:52});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`electronic_mail_address`:"contact@reindorf.de", `telephone_number`:"034130411", `UNIQUE IMPORT ID`:53});
CREATE (:`Party`:`Organisation`:`UNIQUE IMPORT LABEL` {`name`:"AWW Lieferteile AG", `UNIQUE IMPORT ID`:54});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"04104", `street`:"Dresdenerstraße", `street_number`:"5", `town`:"Leipzig", `UNIQUE IMPORT ID`:55});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:56});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`electronic_mail_address`:"auftrag@aww.de", `telephone_number`:"034144536", `UNIQUE IMPORT ID`:57});
CREATE (:`Party`:`Organisation`:`UNIQUE IMPORT LABEL` {`name`:"Roth-Bergmann GmbH", `UNIQUE IMPORT ID`:58});
CREATE (:`Address`:`Physical_address`:`UNIQUE IMPORT LABEL` {`postal_code`:"01553", `street`:"Gellenstraße", `street_number`:"4", `town`:"Hamburg", `UNIQUE IMPORT ID`:59});
CREATE (:`Postal_address`:`Address`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:60});
CREATE (:`Address`:`Electronic_address`:`UNIQUE IMPORT LABEL` {`electronic_mail_address`:"roth@rothbergmann.de", `telephone_number`:"123455197", `UNIQUE IMPORT ID`:61});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:10:07.375Z", `UNIQUE IMPORT ID`:62});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail134002", `UNIQUE IMPORT ID`:63});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docmail", `UNIQUE IMPORT ID`:64});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:11:29.041Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e45e53412016-03-22 02:11:29.041/Beispielmail.txt", `UNIQUE IMPORT ID`:65});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:66});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail134002", `UNIQUE IMPORT ID`:67});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"e-Mail Anfrage über Produktfeatures", `type_of`:"TITLE", `UNIQUE IMPORT ID`:68});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Correspondence", `id`:"BC", `UNIQUE IMPORT ID`:69});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:21:05.143Z", `UNIQUE IMPORT ID`:70});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail134211", `UNIQUE IMPORT ID`:71});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docmail", `UNIQUE IMPORT ID`:72});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:23:50.088Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e45f7bb12016-03-22 02:23:50.088/Beispielmail2.txt", `UNIQUE IMPORT ID`:73});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:74});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail134211", `UNIQUE IMPORT ID`:75});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"e-Mail Antwort über Produktfeatures", `type_of`:"TITLE", `UNIQUE IMPORT ID`:76});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Correspondence", `id`:"BC", `UNIQUE IMPORT ID`:77});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:53:32.613Z", `UNIQUE IMPORT ID`:78});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docbestell55010", `UNIQUE IMPORT ID`:79});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docbestell", `UNIQUE IMPORT ID`:80});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:54:49.740Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@313631702016-03-22 02:54:49.74/Beispielbestellung.txt", `UNIQUE IMPORT ID`:81});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"Bestellung von 3 Desktopcomputern", `type_of`:"TITLE", `UNIQUE IMPORT ID`:82});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Order and delivery documents", `id`:"CD", `UNIQUE IMPORT ID`:83});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:84});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docbestell55010", `UNIQUE IMPORT ID`:85});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:56:24.153Z", `UNIQUE IMPORT ID`:86});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges553516", `UNIQUE IMPORT ID`:87});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges", `UNIQUE IMPORT ID`:88});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T01:58:48.771Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0bfaa1a2016-03-22 02:58:48.771/Beispieldokument.txt", `UNIQUE IMPORT ID`:89});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"Lieferschein für Bestellung", `type_of`:"TITLE", `UNIQUE IMPORT ID`:90});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Order and delivery documents", `id`:"CD", `UNIQUE IMPORT ID`:91});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:92});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges553516", `UNIQUE IMPORT ID`:93});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T02:00:29.758Z", `UNIQUE IMPORT ID`:94});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung51045", `UNIQUE IMPORT ID`:95});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung", `UNIQUE IMPORT ID`:96});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T02:02:24.581Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@7104ff0a2016-03-22 03:02:24.581/Beispielrechnung.txt", `UNIQUE IMPORT ID`:97});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"Rechnung für Bestellung", `type_of`:"TITLE", `UNIQUE IMPORT ID`:98});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Invoice documents", `id`:"CE", `UNIQUE IMPORT ID`:99});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:100});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung51045", `UNIQUE IMPORT ID`:101});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:23:13.687Z", `UNIQUE IMPORT ID`:102});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docinfo120013", `UNIQUE IMPORT ID`:103});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docinfo", `UNIQUE IMPORT ID`:104});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:27:01.365Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@713df9e02016-03-22 04:27:01.365/Beispielbericht.txt", `UNIQUE IMPORT ID`:105});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"Wöchentlicher Statusbericht der Geschäftsführung", `type_of`:"TITLE", `UNIQUE IMPORT ID`:106});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Reports", `id`:"BB", `UNIQUE IMPORT ID`:107});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:108});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docinfo120013", `UNIQUE IMPORT ID`:109});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:29:06.006Z", `UNIQUE IMPORT ID`:110});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docstörmeldung4319", `UNIQUE IMPORT ID`:111});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docstörmeldung", `UNIQUE IMPORT ID`:112});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:30:53.345Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@c5d16a862016-03-22 04:30:53.345/Störmeldung.txt", `UNIQUE IMPORT ID`:113});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docstörmeldung4319", `UNIQUE IMPORT ID`:114});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:32:29.245Z", `UNIQUE IMPORT ID`:115});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail135421", `UNIQUE IMPORT ID`:116});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docmail", `UNIQUE IMPORT ID`:117});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:35:36.170Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e46fd18b2016-03-22 04:35:36.17/Bericht an zuständigen Monteur.txt", `UNIQUE IMPORT ID`:118});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Technical reports", `id`:"DD", `UNIQUE IMPORT ID`:119});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:120});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail135421", `UNIQUE IMPORT ID`:121});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:39:20.543Z", `UNIQUE IMPORT ID`:122});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554942", `UNIQUE IMPORT ID`:123});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges", `UNIQUE IMPORT ID`:124});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:41:11.053Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0d0ac262016-03-22 04:41:11.053/benötigte Teile.txt", `UNIQUE IMPORT ID`:125});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Parts lists", `id`:"PB", `UNIQUE IMPORT ID`:126});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:127});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554942", `UNIQUE IMPORT ID`:128});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:44:06.940Z", `UNIQUE IMPORT ID`:129});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docbestell55443", `UNIQUE IMPORT ID`:130});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docbestell", `UNIQUE IMPORT ID`:131});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:47:25.938Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@31398d722016-03-22 04:47:25.938/Beispielbestellung.txt", `UNIQUE IMPORT ID`:132});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Order and delivery documents", `id`:"CD", `UNIQUE IMPORT ID`:133});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:134});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docbestell55443", `UNIQUE IMPORT ID`:135});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:49:43.284Z", `UNIQUE IMPORT ID`:136});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554970", `UNIQUE IMPORT ID`:137});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges", `UNIQUE IMPORT ID`:138});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:51:06.193Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0d120472016-03-22 04:51:06.193/Beispiellieferschein.txt", `UNIQUE IMPORT ID`:139});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Order and delivery documents", `id`:"CD", `UNIQUE IMPORT ID`:140});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:141});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554970", `UNIQUE IMPORT ID`:142});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:53:10.418Z", `UNIQUE IMPORT ID`:143});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung51108", `UNIQUE IMPORT ID`:144});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung", `UNIQUE IMPORT ID`:145});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:54:49.259Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@7106d4a42016-03-22 04:54:49.259/Beispielrechnung.txt", `UNIQUE IMPORT ID`:146});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Invoice", `id`:"CE", `UNIQUE IMPORT ID`:147});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:148});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung51108", `UNIQUE IMPORT ID`:149});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:55:40.300Z", `UNIQUE IMPORT ID`:150});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554946", `UNIQUE IMPORT ID`:151});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges", `UNIQUE IMPORT ID`:152});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T03:56:57.326Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0d17eda2016-03-22 04:56:57.326/Bericht.txt", `UNIQUE IMPORT ID`:153});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Technical reports", `id`:"DD", `UNIQUE IMPORT ID`:154});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:155});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554946", `UNIQUE IMPORT ID`:156});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T04:36:15.938Z", `UNIQUE IMPORT ID`:157});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges555001", `UNIQUE IMPORT ID`:158});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges", `UNIQUE IMPORT ID`:159});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T04:39:19.561Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0dba3f32016-03-22 05:39:19.561/Version1.txt", `UNIQUE IMPORT ID`:160});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"Ausarbeitung eines Konzeptes zur Einrichtung einer neuen Controlling-Abteilung", `type_of`:"TITLE", `UNIQUE IMPORT ID`:161});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Technical reports", `id`:"DD", `UNIQUE IMPORT ID`:162});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:163});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges555001", `UNIQUE IMPORT ID`:164});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T04:40:36.312Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0dbba792016-03-22 05:40:36.312/Version2.txt", `UNIQUE IMPORT ID`:165});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges555001", `UNIQUE IMPORT ID`:166});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T04:40:44.972Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0dbc1fb2016-03-22 05:40:44.972/Version3.txt", `UNIQUE IMPORT ID`:167});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges555001", `UNIQUE IMPORT ID`:168});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-22T04:40:51.656Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0dbc97d2016-03-22 05:40:51.656/Version4.txt", `UNIQUE IMPORT ID`:169});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges555001", `UNIQUE IMPORT ID`:170});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:03:58.396Z", `UNIQUE IMPORT ID`:171});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:172});
CREATE (:`Document_id_domain`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges", `UNIQUE IMPORT ID`:173});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:08:46.250Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:174});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:175});
CREATE (:`Document_class`:`UNIQUE IMPORT LABEL` {`description`:"Documents regarding changes", `id`:"BH", `UNIQUE IMPORT ID`:176});
CREATE (:`Classification_system`:`UNIQUE IMPORT LABEL` {`id`:"IEC 61355", `UNIQUE IMPORT ID`:177});
CREATE (:`Description`:`UNIQUE IMPORT LABEL` {`language_code`:"de", `textual_description`:"Ideensammlung für ein besseres Unternehmen", `type_of`:"TITLE", `UNIQUE IMPORT ID`:178});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:179});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:30:07.673Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:180});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:181});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:182});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:32:04.667Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:183});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:184});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:185});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:33:12.599Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:186});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:187});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:188});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:34:11.827Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:189});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:190});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:191});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:35:33.708Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:192});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:193});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:194});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:36:37.547Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:195});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:196});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:197});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:37:20.308Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:198});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:199});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:200});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:38:10.718Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:201});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:202});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:203});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-03-23T03:39:24.563Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e24e973e2016-03-23 04:08:46.25/Beispieldokument.txt", `UNIQUE IMPORT ID`:204});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges560947", `UNIQUE IMPORT ID`:205});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"EDITOR", `UNIQUE IMPORT ID`:206});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T07:42:54.273Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e45e53412016-03-22 02:11:29.041/Beispielmail.txt", `UNIQUE IMPORT ID`:207});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail134002", `UNIQUE IMPORT ID`:208});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T07:46:08.205Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0bfaa1a2016-03-22 02:58:48.771/Beispieldokument.txt", `UNIQUE IMPORT ID`:209});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges553516", `UNIQUE IMPORT ID`:210});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T07:46:25.176Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0bfaa1a2016-03-22 02:58:48.771/Beispieldokument.txt", `UNIQUE IMPORT ID`:211});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges553516", `UNIQUE IMPORT ID`:212});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T07:48:11.131Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@7104ff0a2016-03-22 03:02:24.581/Beispielrechnung.txt", `UNIQUE IMPORT ID`:213});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docrechnung51045", `UNIQUE IMPORT ID`:214});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T07:53:40.988Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e46fd18b2016-03-22 04:35:36.17/Bericht an zuständigen Monteur.txt", `UNIQUE IMPORT ID`:215});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docmail135421", `UNIQUE IMPORT ID`:216});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T07:56:06.065Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@31398d722016-03-22 04:47:25.938/Beispielbestellung.txt", `UNIQUE IMPORT ID`:217});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docbestell55443", `UNIQUE IMPORT ID`:218});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T08:06:18.868Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@e0d120472016-03-22 04:51:06.193/Beispiellieferschein.txt", `UNIQUE IMPORT ID`:219});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docsonstiges554970", `UNIQUE IMPORT ID`:220});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T08:08:45.467Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@713df9e02016-03-22 04:27:01.365/Beispielbericht.txt", `UNIQUE IMPORT ID`:221});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docinfo120013", `UNIQUE IMPORT ID`:222});
CREATE (:`Document`:`UNIQUE IMPORT LABEL` {`created_at`:"2016-04-03T08:10:37.843Z", `path_to_file`:"documentrepository/org.blub.domain.Document_id@713df9e02016-03-22 04:27:01.365/Beispielbericht.txt", `UNIQUE IMPORT ID`:223});
CREATE (:`Document_id`:`UNIQUE IMPORT LABEL` {`id`:"docinfo120013", `UNIQUE IMPORT ID`:224});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"OWNER", `UNIQUE IMPORT ID`:225});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"AUTHOR", `UNIQUE IMPORT ID`:226});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"CREATOR", `UNIQUE IMPORT ID`:227});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"CREATOR", `UNIQUE IMPORT ID`:228});
CREATE (:`Person_role`:`Party_role`:`UNIQUE IMPORT LABEL` {`role`:"LOCAL_REPRESENTATIVE", `UNIQUE IMPORT ID`:229});
CREATE (:`Party_role`:`Organisation_role`:`UNIQUE IMPORT LABEL` {`role`:"SUPPLIER", `UNIQUE IMPORT ID`:230});
CREATE (:`Party_role`:`Organisation_role`:`UNIQUE IMPORT LABEL` {`role`:"SUPPLIER", `UNIQUE IMPORT ID`:231});
CREATE (:`Party_role`:`Organisation_role`:`UNIQUE IMPORT LABEL` {`role`:"VENDOR", `UNIQUE IMPORT ID`:232});
commit
begin
CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT node.`UNIQUE IMPORT ID` IS UNIQUE;
commit
schema await
begin
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:1}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:2}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:3}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:4}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:5}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:4}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:6}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:4}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:7}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:8}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:9}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:8}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:10}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:8}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:11}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:12}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:13}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:12}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:14}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:12}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:15}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:16}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:17}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:16}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:18}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:16}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:19}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:21}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:22}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:23}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:24}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:25}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:24}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:26}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:24}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:27}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:28}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:29}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:28}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:30}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:28}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:31}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:32}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:33}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:32}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:34}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:32}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:35}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:36}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:37}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:36}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:38}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:36}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:39}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:51}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:52}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:53}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:55}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:56}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:57}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:58}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:59}) CREATE (n1)-[:`relFromPartyToPhysicalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:58}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:60}) CREATE (n1)-[:`relFromPartyToPostalAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:58}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:61}) CREATE (n1)-[:`relFromPartyToElectronicAddress`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:62}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:63}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:63}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:64}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:62}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:65}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:67}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:67}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:64}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:65}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:68}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:65}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:65}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:69}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:69}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:66}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:62}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:65}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:70}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:71}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:71}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:72}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:70}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:73}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:75}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:75}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:72}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:73}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:76}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:73}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:73}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:77}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:77}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:74}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:70}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:73}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:78}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:78}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:79}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:79}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:80}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:82}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:85}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:80}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:83}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:83}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:84}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:85}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:78}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:86}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:86}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:87}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:87}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:88}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:89}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:90}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:93}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:88}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:89}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:89}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:91}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:91}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:92}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:89}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:93}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:86}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:89}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:94}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:94}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:95}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:95}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:96}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:97}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:98}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:101}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:96}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:97}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:97}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:99}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:99}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:100}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:97}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:101}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:94}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:97}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:102}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:103}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:103}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:104}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:105}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:106}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:105}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:107}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:107}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:108}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:105}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:109}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:109}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:104}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:102}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:105}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:110}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:111}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:111}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:112}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:110}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:114}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:114}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:112}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:113}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:110}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:113}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:115}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:116}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:116}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:117}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:115}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:118}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:119}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:119}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:120}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:118}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:121}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:121}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:117}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:118}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:115}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:118}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:123}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:123}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:124}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:125}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:126}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:126}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:127}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:125}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:128}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:128}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:124}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:125}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:122}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:125}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:129}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:130}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:130}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:131}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:129}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:132}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:133}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:133}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:134}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:132}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:135}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:135}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:131}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:132}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:129}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:132}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:136}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:137}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:137}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:138}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:136}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:140}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:140}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:141}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:142}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:142}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:138}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:136}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:139}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:143}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:144}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:144}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:145}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:143}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:147}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:147}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:148}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:149}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:149}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:145}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:146}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:143}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:146}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:151}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:151}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:152}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:154}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:154}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:155}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:156}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:156}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:152}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:150}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:153}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:157}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:158}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:158}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:159}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:161}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:162}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:162}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:163}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:164}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:164}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:159}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:157}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:160}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:161}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:162}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:166}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:166}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:159}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:160}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:165}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:167}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:161}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:167}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:162}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:167}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:168}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:168}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:159}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:165}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:167}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:169}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:161}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:169}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:162}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:169}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:170}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:170}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:159}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:167}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:169}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:171}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:172}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:172}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:175}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:175}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:177}) CREATE (n1)-[:`USES__CLASSIFICATION__SYSTEM`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:171}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:174}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:179}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:174}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:179}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:180}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:181}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:181}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:180}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:180}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:174}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:180}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:182}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:180}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:182}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:4}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:183}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:184}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:184}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:183}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:183}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:180}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:183}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:183}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:185}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:8}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:186}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:187}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:187}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:186}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:186}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:183}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:186}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:188}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:186}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:188}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:12}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:189}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:190}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:190}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:189}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:189}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:186}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:189}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:191}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:189}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:191}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:16}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:192}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:193}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:193}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:192}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:192}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:189}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:192}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:194}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:192}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:194}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:195}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:196}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:196}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:195}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:195}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:192}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:195}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:195}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:197}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:24}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:198}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:199}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:199}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:198}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:198}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:195}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:198}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:200}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:198}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:200}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:28}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:201}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:202}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:202}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:201}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:201}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:198}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:201}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:203}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:201}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:203}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:32}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:205}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:205}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:173}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:176}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:178}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:201}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:206}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:206}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:36}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:69}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:68}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:208}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:208}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:64}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:73}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"AFFECTING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:65}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:91}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:90}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:210}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:210}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:88}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:89}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:91}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:90}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:212}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:212}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:88}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:209}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:213}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:99}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:213}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:98}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:213}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:214}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:214}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:96}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:213}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:48}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:213}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:97}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:213}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:215}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:119}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:215}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:216}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:216}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:117}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:215}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:215}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:113}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:118}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:215}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:133}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:218}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:218}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:131}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:125}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:132}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:219}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:140}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:219}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:220}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:220}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:138}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:219}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:40}) CREATE (n1)-[:`relFromDocumentToExternalObject`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:219}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:139}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:219}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:107}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:106}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:222}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:222}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:104}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:105}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:221}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:107}) CREATE (n1)-[:`relFromDocumentToDocumentClass`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"AFFECTING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:106}) CREATE (n1)-[:`relFromDocumentToDescription`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:224}) CREATE (n1)-[:`relFromDocumentToDocumentId`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:224}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:104}) CREATE (n1)-[:`relFromDocumentIdToDocumentIdDomain`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:204}) CREATE (n1)-[:`relFromDocumentToDocument` {`relation_type`:"REFERENCING"}]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:221}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}) CREATE (n1)-[:`referenceToNewVersion`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:225}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:225}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:226}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:226}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:227}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:227}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:207}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:228}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:229}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}) CREATE (n1)-[:`relFromPersonRoleToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:229}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:223}) CREATE (n1)-[:`relFromPersonRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:230}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:81}) CREATE (n1)-[:`relFromOrganisationRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:230}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:58}) CREATE (n1)-[:`relFromOrganisationRoleToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:231}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:211}) CREATE (n1)-[:`relFromOrganisationRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:231}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:58}) CREATE (n1)-[:`relFromOrganisationRoleToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:217}) CREATE (n1)-[:`relFromOrganisationRoleToDocument`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:232}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}) CREATE (n1)-[:`relFromOrganisationRoleToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:24}) CREATE (n1)-[:`relFromPersonToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:28}) CREATE (n1)-[:`relFromPersonToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:8}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:36}) CREATE (n1)-[:`relFromPersonToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:0}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}) CREATE (n1)-[:`relFromPersonToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:16}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}) CREATE (n1)-[:`relFromPersonToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}) CREATE (n1)-[:`relFromOrganisationToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:58}) CREATE (n1)-[:`relFromOrganisationToOrganisation`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:54}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:4}) CREATE (n1)-[:`relFromOrganisationToPerson`]->(n2);
MATCH (n1:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:50}), (n2:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`:20}) CREATE (n1)-[:`relFromOrganisationToPerson`]->(n2);
commit
begin
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 1000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
commit
begin
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT node.`UNIQUE IMPORT ID` IS UNIQUE;
commit
